#!/bin/bash

# Script de test SSO après configuration de l'URI de redirection

echo "================================="
echo "Test de connexion SSO"
echo "================================="
echo ""
echo "1. Ouvrez votre navigateur et allez à :"
echo ""
echo "http://localhost:4999/api/auth/sso/azure/login/cb859f98-291e-41b2-b30f-2287c2699205"
echo ""
echo "2. Connectez-vous avec votre compte Microsoft"
echo ""
echo "3. Si tout fonctionne, vous devriez recevoir un JSON avec:"
echo "   - access_token"
echo "   - refresh_token"
echo "   - user info"
echo ""
echo "================================="
echo "En cas d'erreur AADSTS500113:"
echo "================================="
echo "L'URI n'est pas configurée. Dans Azure Portal:"
echo ""
echo "Client ID: 28d84fdd-1d63-4257-8543-86294a55aa80"
echo "URI à ajouter: http://localhost:4999/api/auth/sso/azure/callback"
echo ""
echo "Platform type: Web (pas SPA!)"
echo "================================="