"""
Marshmallow schemas for File model validation and serialization.

This module provides schemas for file-related operations. Unlike other models,
File records are immutable and created only as part of the document upload process.
Files cannot be created, updated, or deleted directly via API endpoints.

Schema provided:
- FileSchema: Read-only schema for File model (all fields dump_only)
- FileResponseSchema: For API responses (same as FileSchema)

File Management Context:
- Files are created automatically during document upload
- MD5 hash is calculated from uploaded file content
- Deduplication: If file with same MD5 exists in tenant database, reuse it
- Files are stored in S3 with path: tenants/{tenant_id}/files/{md5_prefix}/{md5_hash}_{file_uuid}
- Multiple documents can reference the same file_id (deduplication)
- Files are never deleted (referenced by documents, managed by lifecycle policies)

All fields are dump_only since files are immutable once created.

Pre-instantiated schema instances are provided at the bottom of this file for
convenient import and use in routes and services.

Usage:
    from app.schemas import file_response_schema

    # Serialize file object for API response
    result = file_response_schema.dump(file)
"""

from marshmallow import Schema, fields
import logging

logger = logging.getLogger(__name__)


class FileSchema(Schema):
    """
    Base schema for File model with all fields.

    This schema includes all fields from the File model and is used primarily
    for serializing File objects in API responses. All fields are dump_only
    since files are immutable and managed internally by the system.

    Fields:
        id: UUID primary key (auto-generated by database)
        md5_hash: MD5 hash of file content (calculated during upload, 32 hex chars)
        s3_path: S3 object path (auto-generated, format: tenants/{tenant_id}/files/{prefix}/{hash}_{uuid})
        file_size: File size in bytes (calculated during upload)
        created_at: Creation timestamp (auto-generated by database)

    Note: Files do not have updated_at or user_id fields because:
    - Files are immutable (no updates possible)
    - Files are shared across documents (not owned by specific user)
    - Multiple documents can reference the same file_id via MD5 deduplication

    Example output:
        {
            "id": "456e7890-e89b-12d3-a456-426614174001",
            "md5_hash": "5d41402abc4b2a76b9719d911017c592",
            "s3_path": "tenants/tenant_id/files/5d/41/5d41402abc4b2a76b9719d911017c592_456e7890-e89b-12d3-a456-426614174001",
            "file_size": 1048576,
            "created_at": "2024-01-01T00:00:00Z"
        }
    """
    id = fields.UUID(dump_only=True)
    md5_hash = fields.Str(dump_only=True)
    s3_path = fields.Str(dump_only=True)
    file_size = fields.Integer(dump_only=True)
    created_at = fields.DateTime(dump_only=True)


class FileResponseSchema(Schema):
    """
    Schema for serializing File objects in API responses.

    This schema is functionally identical to FileSchema but provided separately
    for consistency with other model schemas (User, Tenant, Document all have
    separate ResponseSchema variants).

    All fields are dump_only (read-only) since files are immutable and this is
    purely for output serialization.

    Fields included:
        id: File UUID
        md5_hash: MD5 hash of file content (32 hex characters)
        s3_path: S3 storage path
        file_size: File size in bytes
        created_at: When file was created

    Use cases:
    - Included in DocumentWithFileResponseSchema to show file details
    - Returned when querying file metadata (admin/debug endpoints)
    - Used in document deduplication responses

    Example output:
        {
            "id": "456e7890-e89b-12d3-a456-426614174001",
            "md5_hash": "5d41402abc4b2a76b9719d911017c592",
            "s3_path": "tenants/123e4567-e89b-12d3-a456-426614174000/files/5d/41/5d41402abc4b2a76b9719d911017c592_456e7890",
            "file_size": 1048576,
            "created_at": "2024-01-01T00:00:00Z"
        }
    """
    id = fields.UUID(dump_only=True)
    md5_hash = fields.Str(dump_only=True)
    s3_path = fields.Str(dump_only=True)
    file_size = fields.Integer(dump_only=True)
    created_at = fields.DateTime(dump_only=True)


# Pre-instantiated schema instances for convenient import
# These can be imported and used directly in routes and services

# Base schema (can be used for any file serialization)
file_schema = FileSchema()

# Response schema (preferred for API responses)
file_response_schema = FileResponseSchema()

# For serializing lists of files (rarely needed, but provided for completeness)
files_response_schema = FileResponseSchema(many=True)


# Export all schemas and instances
__all__ = [
    # Schema classes
    'FileSchema',
    'FileResponseSchema',

    # Pre-instantiated schema instances
    'file_schema',
    'file_response_schema',
    'files_response_schema',
]
