"""
Marshmallow schemas for Tenant model validation and serialization.

This module provides comprehensive validation schemas for all tenant-related operations:
- TenantSchema: Base schema with all Tenant model fields
- TenantCreateSchema: For creating new tenants (POST /api/tenants)
- TenantUpdateSchema: For updating tenant information (PUT /api/tenants/{id})
- TenantResponseSchema: For API responses (all fields dump_only)

All schemas include:
- Field validation with Marshmallow validators
- Data normalization via @post_load hooks
- Proper handling of auto-generated fields (id, database_name, timestamps)

Pre-instantiated schema instances are provided at the bottom of this file for
convenient import and use in routes and services.

Usage:
    from app.schemas import tenant_create_schema, tenant_response_schema

    # Validate input
    data = tenant_create_schema.load(request.json)

    # Serialize output
    result = tenant_response_schema.dump(tenant)
"""

from marshmallow import Schema, fields, validates, ValidationError, post_load, validate
import logging

logger = logging.getLogger(__name__)


class TenantSchema(Schema):
    """
    Base schema for Tenant model with all fields.

    This schema includes all fields from the Tenant model and can be used
    as a reference or extended for specific use cases.

    Fields:
        id: UUID primary key (auto-generated, dump_only)
        name: Tenant organization name (required, 1-255 chars)
        database_name: PostgreSQL database name (auto-generated, dump_only)
        is_active: Soft delete flag (default True)
        created_at: Creation timestamp (auto-generated, dump_only)
        updated_at: Last update timestamp (auto-generated, dump_only)
        created_by: UUID of user who created tenant (dump_only)
    """
    id = fields.UUID(dump_only=True)
    name = fields.Str(required=True, validate=validate.Length(min=1, max=255))
    database_name = fields.Str(dump_only=True)  # Auto-generated from name
    is_active = fields.Boolean(load_default=True)
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)
    created_by = fields.UUID(dump_only=True)

    @validates('name')
    def validate_name(self, value):
        """
        Validate tenant name format.

        Rules:
        - Must not be empty or only whitespace
        - Must be between 1 and 255 characters after trimming

        Args:
            value: The tenant name to validate

        Raises:
            ValidationError: If name is empty or invalid
        """
        if not value or not value.strip():
            raise ValidationError("Tenant name cannot be empty or only whitespace")

        if len(value.strip()) > 255:
            raise ValidationError("Tenant name cannot exceed 255 characters")

        logger.debug(f"Validated tenant name: {value.strip()}")

    @post_load
    def normalize_data(self, data, **kwargs):
        """
        Normalize input data after validation.

        Transformations:
        - Trim whitespace from name

        Args:
            data: The validated data dictionary

        Returns:
            Normalized data dictionary
        """
        if 'name' in data:
            data['name'] = data['name'].strip()
            logger.debug(f"Normalized tenant name: {data['name']}")

        return data


class TenantCreateSchema(Schema):
    """
    Schema for creating new tenants (POST /api/tenants).

    This schema is used when a user creates a new tenant organization.
    The database_name will be auto-generated from the tenant name by the
    Tenant model, and the creator will automatically be added as an admin.

    Required fields:
        name: Tenant organization name (1-255 chars)

    Auto-generated fields (not included in input):
        id: UUID (generated by database)
        database_name: PostgreSQL database name (generated from name)
        is_active: Default True
        created_at, updated_at: Timestamps
        created_by: User ID from JWT token

    Example:
        {
            "name": "Acme Corporation"
        }
    """
    name = fields.Str(required=True, validate=validate.Length(min=1, max=255))

    @validates('name')
    def validate_name(self, value):
        """
        Validate tenant name format.

        Rules:
        - Must not be empty or only whitespace
        - Must be between 1 and 255 characters after trimming

        Args:
            value: The tenant name to validate

        Raises:
            ValidationError: If name is empty or invalid
        """
        if not value or not value.strip():
            raise ValidationError("Tenant name cannot be empty or only whitespace")

        if len(value.strip()) > 255:
            raise ValidationError("Tenant name cannot exceed 255 characters")

        logger.debug(f"Validated tenant name for creation: {value.strip()}")

    @post_load
    def normalize_data(self, data, **kwargs):
        """
        Normalize input data after validation.

        Transformations:
        - Trim whitespace from name

        Args:
            data: The validated data dictionary

        Returns:
            Normalized data dictionary
        """
        if 'name' in data:
            data['name'] = data['name'].strip()
            logger.debug(f"Normalized tenant name for creation: {data['name']}")

        return data


class TenantUpdateSchema(Schema):
    """
    Schema for updating tenant information (PUT /api/tenants/{id}).

    This schema is used when updating tenant metadata. All fields are optional
    since this is a partial update endpoint.

    Immutable fields (cannot be updated):
        id: Cannot change primary key
        database_name: Cannot rename database after creation
        created_at, created_by: Audit trail immutable

    Updatable fields:
        name: Tenant organization name (optional, 1-255 chars)
        is_active: Soft delete flag (optional)

    Note: Changing is_active to False is a soft delete (deactivate tenant).
    Only admin users can update tenant information.

    Example:
        {
            "name": "Acme Corporation (Updated)",
            "is_active": true
        }
    """
    name = fields.Str(validate=validate.Length(min=1, max=255))
    is_active = fields.Boolean()

    @validates('name')
    def validate_name(self, value):
        """
        Validate tenant name format (if provided).

        Rules:
        - Must not be empty or only whitespace (if provided)
        - Must be between 1 and 255 characters after trimming

        Args:
            value: The tenant name to validate

        Raises:
            ValidationError: If name is empty or invalid
        """
        if value is not None:
            if not value or not value.strip():
                raise ValidationError("Tenant name cannot be empty or only whitespace")

            if len(value.strip()) > 255:
                raise ValidationError("Tenant name cannot exceed 255 characters")

            logger.debug(f"Validated tenant name for update: {value.strip()}")

    @post_load
    def normalize_data(self, data, **kwargs):
        """
        Normalize input data after validation.

        Transformations:
        - Trim whitespace from name (if provided)

        Args:
            data: The validated data dictionary

        Returns:
            Normalized data dictionary
        """
        if 'name' in data and data['name'] is not None:
            data['name'] = data['name'].strip()
            logger.debug(f"Normalized tenant name for update: {data['name']}")

        return data


class TenantResponseSchema(Schema):
    """
    Schema for serializing Tenant objects in API responses.

    This schema is used for all API responses that return tenant data.
    All fields are dump_only (read-only) since this is purely for output.

    Fields included:
        id: Tenant UUID
        name: Tenant organization name
        database_name: PostgreSQL database name (for reference)
        is_active: Whether tenant is active
        created_at: When tenant was created
        updated_at: When tenant was last updated
        created_by: UUID of user who created tenant

    Optional stats (controlled by include_stats parameter):
        user_count: Number of users in tenant
        database_exists: Whether tenant database exists

    Example output:
        {
            "id": "123e4567-e89b-12d3-a456-426614174000",
            "name": "Acme Corporation",
            "database_name": "tenant_acme_corp_a1b2c3d4",
            "is_active": true,
            "created_at": "2024-01-01T00:00:00Z",
            "updated_at": "2024-01-01T00:00:00Z",
            "created_by": "456e7890-e89b-12d3-a456-426614174001"
        }
    """
    id = fields.UUID(dump_only=True)
    name = fields.Str(dump_only=True)
    database_name = fields.Str(dump_only=True)
    is_active = fields.Boolean(dump_only=True)
    created_at = fields.DateTime(dump_only=True)
    updated_at = fields.DateTime(dump_only=True)
    created_by = fields.UUID(dump_only=True)

    # Optional stats fields (not always included)
    user_count = fields.Integer(dump_only=True)
    database_exists = fields.Boolean(dump_only=True)


class TenantWithUsersResponseSchema(TenantResponseSchema):
    """
    Extended schema for tenant responses that include user list.

    This schema extends TenantResponseSchema to include a list of users
    with their roles in the tenant. Used for GET /api/tenants/{id} endpoint.

    Additional fields:
        users: List of users in tenant with their roles

    Example output:
        {
            "id": "123e4567-e89b-12d3-a456-426614174000",
            "name": "Acme Corporation",
            "database_name": "tenant_acme_corp_a1b2c3d4",
            "is_active": true,
            "created_at": "2024-01-01T00:00:00Z",
            "updated_at": "2024-01-01T00:00:00Z",
            "created_by": "456e7890-e89b-12d3-a456-426614174001",
            "users": [
                {
                    "user_id": "456e7890-e89b-12d3-a456-426614174001",
                    "email": "admin@acme.com",
                    "role": "admin"
                }
            ]
        }
    """
    users = fields.List(fields.Dict(), dump_only=True)


# Pre-instantiated schema instances for convenient import
# These can be imported and used directly in routes and services

# Base schema (rarely used directly)
tenant_schema = TenantSchema()

# Input validation schemas
tenant_create_schema = TenantCreateSchema()
tenant_update_schema = TenantUpdateSchema()

# Output serialization schemas
tenant_response_schema = TenantResponseSchema()
tenant_with_users_response_schema = TenantWithUsersResponseSchema()

# For serializing lists of tenants
tenants_response_schema = TenantResponseSchema(many=True)


# Export all schemas and instances
__all__ = [
    # Schema classes
    'TenantSchema',
    'TenantCreateSchema',
    'TenantUpdateSchema',
    'TenantResponseSchema',
    'TenantWithUsersResponseSchema',

    # Pre-instantiated schema instances
    'tenant_schema',
    'tenant_create_schema',
    'tenant_update_schema',
    'tenant_response_schema',
    'tenant_with_users_response_schema',
    'tenants_response_schema',
]
