"""Move SSO fields from User to UserAzureIdentity

Revision ID: 0783c3a365b1
Revises: fb48b3669e3b
Create Date: 2025-11-10 21:27:59.037304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0783c3a365b1'
down_revision = 'fb48b3669e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_azure_identities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sso_metadata', sa.JSON(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('sso_provider')
        batch_op.drop_column('sso_metadata')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sso_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Additional SSO metadata (job title, department, etc.)'))
        batch_op.add_column(sa.Column('sso_provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment="SSO provider used by this user (e.g., 'azure_ad')"))

    with op.batch_alter_table('user_azure_identities', schema=None) as batch_op:
        batch_op.drop_column('sso_metadata')

    # ### end Alembic commands ###
