"""Initial migration

Revision ID: 1b5f6d29b7ed
Revises: 
Create Date: 2025-11-18 18:20:25.978061

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1b5f6d29b7ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('database_name', sa.String(length=63), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auth_method', sa.String(length=20), nullable=False),
    sa.Column('sso_domain_whitelist', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('sso_auto_provisioning', sa.Boolean(), nullable=True),
    sa.Column('sso_default_role', sa.String(length=20), nullable=True),
    sa.Column('tsa_enabled', sa.Boolean(), nullable=False),
    sa.Column('tsa_provider', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was last updated (UTC)'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of user who created this record (nullable for self-registration)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('database_name')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index('ix_tenants_database_name', ['database_name'], unique=True)
        batch_op.create_index('ix_tenants_name_active', ['name', 'is_active'], unique=False)

    op.create_table('users',
    sa.Column('first_name', sa.String(length=100), nullable=False, comment="User's first name"),
    sa.Column('last_name', sa.String(length=100), nullable=False, comment="User's last name"),
    sa.Column('email', sa.String(length=255), nullable=False, comment="User's email address (unique, used for login)"),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='Bcrypt hashed password (optional for SSO-only users)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether user account is active (can login)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was last updated (UTC)'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of user who created this record (nullable for self-registration)'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index('ix_users_email_active', ['email', 'is_active'], unique=False)

    op.create_table('tenant_sso_configs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('provider_tenant_id', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret', sa.String(length=500), nullable=False),
    sa.Column('redirect_uri', sa.String(length=500), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('config_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was last updated (UTC)'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of user who created this record (nullable for self-registration)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenant_sso_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_sso_configs_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_sso_configs_provider_type'), ['provider_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_sso_configs_tenant_id'), ['tenant_id'], unique=True)

    op.create_table('user_azure_identities',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('azure_object_id', sa.String(length=255), nullable=False),
    sa.Column('azure_tenant_id', sa.String(length=255), nullable=False),
    sa.Column('azure_upn', sa.String(length=255), nullable=True),
    sa.Column('azure_display_name', sa.String(length=255), nullable=True),
    sa.Column('encrypted_access_token', sa.Text(), nullable=True),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=True),
    sa.Column('encrypted_id_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refresh_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sso_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was last updated (UTC)'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of user who created this record (nullable for self-registration)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tenant_id', name='_user_tenant_azure_uc')
    )
    with op.batch_alter_table('user_azure_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_azure_identities_azure_object_id'), ['azure_object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_azure_identities_azure_tenant_id'), ['azure_tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_azure_identities_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_azure_identities_user_id'), ['user_id'], unique=False)

    op.create_table('user_tenant_associations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'user', 'viewer')", name='valid_role_check'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'tenant_id')
    )
    with op.batch_alter_table('user_tenant_associations', schema=None) as batch_op:
        batch_op.create_index('ix_user_tenant_role', ['role'], unique=False)
        batch_op.create_index('ix_user_tenant_tenant_id', ['tenant_id'], unique=False)
        batch_op.create_index('ix_user_tenant_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tenant_associations', schema=None) as batch_op:
        batch_op.drop_index('ix_user_tenant_user_id')
        batch_op.drop_index('ix_user_tenant_tenant_id')
        batch_op.drop_index('ix_user_tenant_role')

    op.drop_table('user_tenant_associations')
    with op.batch_alter_table('user_azure_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_azure_identities_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_azure_identities_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_user_azure_identities_azure_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_user_azure_identities_azure_object_id'))

    op.drop_table('user_azure_identities')
    with op.batch_alter_table('tenant_sso_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_sso_configs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_sso_configs_provider_type'))
        batch_op.drop_index(batch_op.f('ix_tenant_sso_configs_is_enabled'))

    op.drop_table('tenant_sso_configs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email_active')
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index('ix_tenants_name_active')
        batch_op.drop_index('ix_tenants_database_name')

    op.drop_table('tenants')
    # ### end Alembic commands ###
