"""Add TSA configuration to tenants

Revision ID: 7ffd4fe46854
Revises: f11f82e2381e
Create Date: 2025-11-12 10:14:43.894832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ffd4fe46854'
down_revision = 'f11f82e2381e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tsa_enabled', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('tsa_provider', sa.String(length=50), nullable=True, server_default='digicert'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('tsa_provider')
        batch_op.drop_column('tsa_enabled')

    # ### end Alembic commands ###
