"""Initial migration

Revision ID: fdb2c85223b8
Revises: 0783c3a365b1
Create Date: 2025-11-11 16:55:37.375626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdb2c85223b8'
down_revision = '0783c3a365b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_sso_configs', schema=None) as batch_op:
        batch_op.alter_column('client_secret',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_sso_configs', schema=None) as batch_op:
        batch_op.alter_column('client_secret',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###
